import {MODEL_ORDER,RECORD_ORDER,CATEGORIES,CATEGORY_COLORS,createDefaultData} from "../data/models.js";
import {saveFile,getFile,deleteAllFiles,addAudit} from "./database.js";
import {toast,escapeHtml,formatBytes,downloadBlob,downloadText} from "./ui.js";

const STORAGE_KEY="MOBILE_RND_DB_DATA_V10";
const PREF_KEY="MOBILE_RND_PREFS_V3";
const AUTH_KEY="RND_AUTH_V3";
const MAX_FILE_SIZE=500*1024*1024;
const ALLOWED=["pdf","xlsx","xls","zip","bin","dwg","csv","doc","docx","ppt","pptx"];
let data=loadData(), prefs=loadPrefs(), currentModel=MODEL_ORDER[0], activeCategory="all", query="", sortMode="default", favoritesOnly=false, selectedRecords=new Set(), recentlyViewed=JSON.parse(localStorage.getItem("MOBILE_RND_RECENT_V1")||"[]"), isAdmin=sessionStorage.getItem(AUTH_KEY)==="true", selectedFile=null;
let favorites=JSON.parse(localStorage.getItem("MOBILE_RND_FAVORITES_V1")||"[]");

function loadData(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||createDefaultData()}catch{return createDefaultData()}}
function saveData(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data))}
function loadPrefs(){try{return {...{theme:"light",accent:"cyan",density:"comfortable",motion:true},...JSON.parse(localStorage.getItem(PREF_KEY))}}catch{return {theme:"light",accent:"cyan",density:"comfortable",motion:true}}}
function savePrefs(){localStorage.setItem(PREF_KEY,JSON.stringify(prefs))}
function currentItems(){return data[currentModel].items}
function itemText(k,item){return [k,item.title,item.category,item.filename,...(item.tags||[]),...(item.subItems||[]).flatMap(s=>[s.name,s.filename,s.size])].join(" ").toLowerCase()}
function markRecent(key){const id=`${currentModel}:${key}`;recentlyViewed=[id,...recentlyViewed.filter(x=>x!==id)].slice(0,8);localStorage.setItem("MOBILE_RND_RECENT_V1",JSON.stringify(recentlyViewed))}
function parseHash(){const m=location.hash.match(/^#record\/([^/]+)\/?([^/]*)$/);if(m&&MODEL_ORDER.includes(m[1])&&currentItemsFor(m[1])[m[2]]){currentModel=m[1];activeCategory="all";query="";setTimeout(()=>focusRecord(m[2]),0)}}
function currentItemsFor(model){return data[model]?.items||{}}

function init(){
  document.getElementById("modelSelect").innerHTML=MODEL_ORDER.map(m=>`<option value="${m}">${m} • ${escapeHtml(data[m].meta.name)}</option>`).join("");
  document.getElementById("uploadModel").innerHTML=MODEL_ORDER.map(m=>`<option value="${m}">${m} • ${escapeHtml(data[m].meta.name)}</option>`).join("");
  const last=localStorage.getItem("MOBILE_RND_LAST_MODEL_V1"); if(last&&MODEL_ORDER.includes(last))currentModel=last;
  document.getElementById("modelSelect").value=currentModel;document.getElementById("uploadModel").value=currentModel;
  renderCategories();renderAll();bindEvents();applyPrefs();parseHash();
}
function renderAll(){renderHero();renderCards();populateUploadRecords();renderAuth();renderRecent();}
function renderHero(){const m=data[currentModel].meta;document.getElementById("activeModelCode").textContent=currentModel;document.getElementById("activeModelName").textContent=m.name;document.getElementById("modelStatus").innerHTML=`<i class="fa-solid fa-circle"></i> ${escapeHtml(m.status)}`;document.getElementById("metaAp").textContent=m.ap;document.getElementById("metaModem").textContent=m.modem;document.getElementById("metaSw").textContent=m.swVersion;document.getElementById("metaLead").textContent=m.leadKorea}
function renderCategories(){document.getElementById("categoryTabs").innerHTML=CATEGORIES.map(c=>`<button class="cat-btn ${activeCategory===c.key?"active":""}" data-cat="${escapeHtml(c.key)}">${escapeHtml(c.label)}</button>`).join("")}
function filteredEntries(){let arr=RECORD_ORDER.map(k=>[k,currentItems()[k]]).filter(([,i])=>i).filter(([k,i])=>{const cat=activeCategory==="all"||i.category===activeCategory;const fav=!favoritesOnly||favorites.includes(`${currentModel}:${k}`);return cat&&fav&&(!query||itemText(k,i).includes(query.toLowerCase()))});if(sortMode==="title")arr.sort((a,b)=>a[1].title.localeCompare(b[1].title));if(sortMode==="category")arr.sort((a,b)=>a[1].category.localeCompare(b[1].category)||a[0].localeCompare(b[0]));if(sortMode==="favorite")arr.sort((a,b)=>Number(favorites.includes(`${currentModel}:${b[0]}`))-Number(favorites.includes(`${currentModel}:${a[0]}`)));return arr}
function renderCards(){const grid=document.getElementById("cardsGrid"),entries=filteredEntries();document.getElementById("recordCount").textContent=`${entries.length} of ${RECORD_ORDER.filter(k=>currentItems()[k]).length} records`;document.getElementById("activeFilters").classList.toggle("hidden",!(query||activeCategory!=="all"||favoritesOnly||sortMode!=="default"));document.getElementById("activeFilters").innerHTML=`${query?`<span class="filter-chip">Search: ${escapeHtml(query)}</span>`:""}${activeCategory!=="all"?`<span class="filter-chip">Category: ${escapeHtml(activeCategory)}</span>`:""}${favoritesOnly?`<span class="filter-chip">Favorites only</span>`:""}${sortMode!=="default"?`<span class="filter-chip">Sort: ${escapeHtml(sortMode)}</span>`:""}`;if(!entries.length){grid.innerHTML=`<div class="empty-state"><i class="fa-solid fa-filter-circle-xmark"></i><h3 class="font-bold mt-3">No records found</h3><p class="text-xs mt-1">Adjust the search or filters.</p><button class="btn btn-light mt-3" data-clear-filters>Clear filters</button></div>`;return}grid.innerHTML=entries.map(([k,i])=>renderCard(k,i)).join("")}
function renderCard(key,item){const color=CATEGORY_COLORS[item.category]||CATEGORY_COLORS.General,tags=(item.tags||[]).map(t=>`<span class="tag">${escapeHtml(t)}</span>`).join("");const favKey=`${currentModel}:${key}`,isFav=favorites.includes(favKey);let files=item.subItems?.length?item.subItems.map((s,i)=>`<div class="file-row"><div class="min-w-0"><div class="file-name">${escapeHtml(s.name)}</div><div class="file-size">${escapeHtml(s.size||"FILE")}</div></div><button class="download-btn" style="background:${color}" data-download="${currentModel}_${key}_${i}" data-filename="${escapeHtml(s.filename)}"><i class="fa-solid fa-download"></i> GET</button></div>`).join(""):`<div class="file-row"><div class="min-w-0"><div class="file-name" title="${escapeHtml(item.filename||"")}">${escapeHtml(item.filename||"Linked record")}</div><div class="file-size">${escapeHtml(item.size||"Master")}</div></div><button class="download-btn" style="background:${color}" data-download="${currentModel}_${key}" data-filename="${escapeHtml(item.filename||key+".txt")}"><i class="fa-solid fa-download"></i> DOWNLOAD</button></div>`;return `<article id="record-${escapeHtml(key)}" class="record-card ${isFav?"is-favorite":""}" data-record="${escapeHtml(key)}"><div class="record-stripe" style="background:${color}"></div><div class="record-body"><div><div class="record-header"><div class="record-title-wrap"><input class="record-check" type="checkbox" data-select-record="${escapeHtml(key)}" ${selectedRecords.has(key)?"checked":""} aria-label="Select record ${escapeHtml(key)}"><div class="record-icon" style="background:${color}"><i class="fa-solid ${escapeHtml(item.icon)}"></i></div><div class="min-w-0"><div class="record-key">RECORD ${escapeHtml(key)}</div><div class="record-title">${escapeHtml(item.title)}</div></div></div><div class="card-actions"><span class="category-label">${escapeHtml(item.category)}</span><button class="favorite-btn ${isFav?"active":""}" data-favorite="${escapeHtml(favKey)}" title="Favorite"><i class="fa-${isFav?"solid":"regular"} fa-star"></i></button></div></div><div class="tags">${tags||'<span class="tag">No additional metadata</span>'}</div></div><div class="file-area">${files}</div><div class="card-footer-actions"><button class="text-action" data-open-record="${escapeHtml(key)}"><i class="fa-solid fa-up-right-and-down-left-from-center"></i> Open</button><button class="text-action" data-copy-record="${escapeHtml(key)}"><i class="fa-regular fa-copy"></i> Copy</button><button class="text-action" data-link-record="${escapeHtml(key)}"><i class="fa-solid fa-link"></i> Link</button></div></div></article>`}
function renderAuth(){const slot=document.getElementById("adminAuthSlot");slot.innerHTML=isAdmin?`<div class="flex gap-1"><button id="uploadBtn" class="btn btn-cyan"><i class="fa-solid fa-cloud-arrow-up"></i> Upload</button><button id="logoutBtn" class="header-icon-btn" title="Logout"><i class="fa-solid fa-right-from-bracket"></i></button></div>`:`<button id="loginBtn" class="btn btn-dark"><i class="fa-solid fa-lock"></i> Admin</button>`;document.getElementById(isAdmin?"uploadBtn":"loginBtn").addEventListener("click",()=>openModal(isAdmin?"uploadModal":"loginModal"));if(isAdmin)document.getElementById("logoutBtn").addEventListener("click",()=>{isAdmin=false;sessionStorage.removeItem(AUTH_KEY);renderAuth();toast("Admin session ended.","info")})}
function populateUploadRecords(){document.getElementById("uploadRecord").innerHTML=RECORD_ORDER.filter(k=>currentItems()[k]).map(k=>`<option value="${k}">[${k}] ${escapeHtml(currentItems()[k].title)}</option>`).join("")}
function openModal(id){document.getElementById(id).classList.remove("hidden")}function closeModal(id){document.getElementById(id).classList.add("hidden")}
function setModel(m){currentModel=m;localStorage.setItem("MOBILE_RND_LAST_MODEL_V1",m);document.getElementById("modelSelect").value=m;document.getElementById("uploadModel").value=m;selectedRecords.clear();renderAll();location.hash=""}
function openRecord(key){markRecent(key);location.hash=`record/${currentModel}/${key}`;renderRecent();focusRecord(key)}
function focusRecord(key){const el=document.getElementById(`record-${key}`);if(el){el.scrollIntoView({behavior:prefs.motion?"smooth":"auto",block:"center"});el.classList.add("record-focus");setTimeout(()=>el.classList.remove("record-focus"),1200)}}
function renderRecent(){const wrap=document.getElementById("recentList");if(!wrap)return;const items=recentlyViewed.map(id=>{const [m,k]=id.split(":");const item=currentItemsFor(m)[k];return item?{m,k,item}:null}).filter(Boolean);wrap.innerHTML=items.length?items.map(x=>`<button class="recent-item" data-recent-model="${x.m}" data-recent-key="${x.k}"><span>${x.m} · ${x.k}</span><strong>${escapeHtml(x.item.title)}</strong></button>`).join(""):"<span class='help-text'>No recently viewed records.</span>"}
function bindEvents(){
  document.getElementById("modelSelect").addEventListener("change",e=>setModel(e.target.value));
  document.getElementById("searchInput").addEventListener("input",e=>{query=e.target.value.trim();document.getElementById("clearSearchBtn").classList.toggle("hidden",!query);renderCards()});
  document.getElementById("clearSearchBtn").addEventListener("click",()=>{query="";document.getElementById("searchInput").value="";document.getElementById("clearSearchBtn").classList.add("hidden");renderCards()});
  document.getElementById("categoryTabs").addEventListener("click",e=>{const b=e.target.closest("[data-cat]");if(b){activeCategory=b.dataset.cat;renderCategories();renderCards()}});
  document.getElementById("cardsGrid").addEventListener("click",e=>{const fav=e.target.closest("[data-favorite]");if(fav){toggleFavorite(fav.dataset.favorite);return}const d=e.target.closest("[data-download]");if(d){downloadRecord(d.dataset.download,d.dataset.filename);return}const o=e.target.closest("[data-open-record]");if(o){openRecord(o.dataset.openRecord);openPresentation(o.dataset.openRecord);return}const c=e.target.closest("[data-copy-record]");if(c){copyRecord(c.dataset.copyRecord);return}const l=e.target.closest("[data-link-record]");if(l){copyLink(l.dataset.linkRecord);return}const clr=e.target.closest("[data-clear-filters]");if(clr)clearFilters()});
  document.getElementById("cardsGrid").addEventListener("change",e=>{const c=e.target.closest("[data-select-record]");if(c){if(c.checked)selectedRecords.add(c.dataset.selectRecord);else selectedRecords.delete(c.dataset.selectRecord);updateSelectionBar()}});
  document.getElementById("copySpecsBtn").addEventListener("click",copySpecs);document.getElementById("exportJsonBtn").addEventListener("click",exportModel);document.getElementById("exportReportBtn").addEventListener("click",exportReport);document.getElementById("settingsBtn").addEventListener("click",()=>openModal("settingsModal"));document.getElementById("themeBtn").addEventListener("click",()=>{prefs.theme=prefs.theme==="dark"?"light":"dark";savePrefs();applyPrefs()});document.getElementById("fullscreenBtn").addEventListener("click",toggleFullscreen);
  document.getElementById("themeSelect").addEventListener("change",e=>{prefs.theme=e.target.value;savePrefs();applyPrefs()});document.getElementById("accentSelect").addEventListener("change",e=>{prefs.accent=e.target.value;savePrefs();applyPrefs()});document.getElementById("densitySelect").addEventListener("change",e=>{prefs.density=e.target.value;savePrefs();applyPrefs()});
  document.getElementById("sortSelect").addEventListener("change",e=>{sortMode=e.target.value;renderCards()});document.getElementById("favoritesToggle").addEventListener("click",()=>{favoritesOnly=!favoritesOnly;document.getElementById("favoritesToggle").classList.toggle("active",favoritesOnly);renderCards()});document.getElementById("compareBtn").addEventListener("click",openCompare);document.getElementById("compareModelA").addEventListener("change",renderComparison);document.getElementById("compareModelB").addEventListener("change",renderComparison);document.getElementById("selectAllBtn").addEventListener("click",()=>{filteredEntries().forEach(([k])=>selectedRecords.add(k));renderCards();updateSelectionBar()});document.getElementById("clearSelectionBtn").addEventListener("click",()=>{selectedRecords.clear();renderCards();updateSelectionBar()});document.getElementById("exportSelectedBtn").addEventListener("click",exportSelected);document.getElementById("printSelectedBtn").addEventListener("click",printSelected);document.getElementById("clearFiltersBtn").addEventListener("click",clearFilters);
  document.getElementById("prevRecordBtn").addEventListener("click",()=>navigateRecord(-1));document.getElementById("nextRecordBtn").addEventListener("click",()=>navigateRecord(1));document.getElementById("presentationBtn").addEventListener("click",()=>{const k=selectedRecords.size===1?[...selectedRecords][0]:filteredEntries()[0]?.[0];if(k)openPresentation(k)});
  document.getElementById("recentList").addEventListener("click",e=>{const b=e.target.closest("[data-recent-key]");if(b){setModel(b.dataset.recentModel);setTimeout(()=>openRecord(b.dataset.recentKey),50)}});
  document.querySelectorAll("[data-close]").forEach(b=>b.addEventListener("click",()=>closeModal(b.dataset.close)));document.querySelectorAll(".modal-backdrop").forEach(b=>b.addEventListener("click",()=>b.parentElement.classList.add("hidden")));
  document.getElementById("loginForm").addEventListener("submit",login);document.getElementById("uploadModel").addEventListener("change",e=>{currentModel=e.target.value;document.getElementById("modelSelect").value=currentModel;renderAll()});document.getElementById("dropZone").addEventListener("click",()=>document.getElementById("fileInput").click());document.getElementById("dropZone").addEventListener("dragover",e=>{e.preventDefault();document.getElementById("dropZone").classList.add("drag-active")});document.getElementById("dropZone").addEventListener("dragleave",()=>document.getElementById("dropZone").classList.remove("drag-active"));document.getElementById("dropZone").addEventListener("drop",e=>{e.preventDefault();document.getElementById("dropZone").classList.remove("drag-active");selectFile(e.dataTransfer.files[0])});document.getElementById("fileInput").addEventListener("change",e=>selectFile(e.target.files[0]));document.getElementById("uploadForm").addEventListener("submit",upload);
  document.getElementById("compactToggle").addEventListener("change",e=>{prefs.density=e.target.checked?"compact":"comfortable";savePrefs();applyPrefs()});document.getElementById("motionToggle").addEventListener("change",e=>{prefs.motion=e.target.checked;savePrefs();applyPrefs()});document.getElementById("backupBtn").addEventListener("click",()=>downloadText(JSON.stringify(data,null,2),`MobileRD_Backup_${dateStamp()}.json`));document.getElementById("resetBtn").addEventListener("click",resetData);
  document.addEventListener("keydown",e=>{if(e.key==="Escape")document.querySelectorAll(".modal:not(.hidden)").forEach(m=>m.classList.add("hidden"));if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();document.getElementById("searchInput").focus()}if(e.key==="/"&&!/[INPUTTEXTAREASELECT]/.test(document.activeElement.tagName)){e.preventDefault();document.getElementById("searchInput").focus()}if(e.key.toLowerCase()==="f"&&!/[INPUTTEXTAREASELECT]/.test(document.activeElement.tagName))toggleFullscreen();if(e.key.toLowerCase()==="p"&&!/[INPUTTEXTAREASELECT]/.test(document.activeElement.tagName)){e.preventDefault();document.getElementById("presentationBtn").click()}});
}
function updateSelectionBar(){document.getElementById("selectionCount").textContent=`${selectedRecords.size} selected`;document.getElementById("selectionBar").classList.toggle("hidden",selectedRecords.size===0)}
function clearFilters(){query="";activeCategory="all";favoritesOnly=false;sortMode="default";document.getElementById("searchInput").value="";document.getElementById("sortSelect").value="default";document.getElementById("favoritesToggle").classList.remove("active");renderCategories();renderCards()}
function applyPrefs(){document.body.classList.toggle("no-motion",!prefs.motion);document.body.dataset.theme=prefs.theme;document.body.dataset.accent=prefs.accent;document.body.dataset.density=prefs.density;document.getElementById("themeSelect").value=prefs.theme;document.getElementById("accentSelect").value=prefs.accent;document.getElementById("densitySelect").value=prefs.density;document.getElementById("motionToggle").checked=prefs.motion;document.getElementById("compactToggle").checked=prefs.density==="compact";document.getElementById("themeIcon").className=`fa-solid fa-${prefs.theme==="dark"?"sun":"moon"}`}
function toggleFavorite(id){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];localStorage.setItem("MOBILE_RND_FAVORITES_V1",JSON.stringify(favorites));renderCards();toast(favorites.includes(id)?"Added to favorites.":"Removed from favorites.","info")}
async function toggleFullscreen(){try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch{toast("Fullscreen is not available.","error")}}
function login(e){e.preventDefault();if(document.getElementById("passwordInput").value==="admin123"){isAdmin=true;sessionStorage.setItem(AUTH_KEY,"true");closeModal("loginModal");document.getElementById("passwordInput").value="";renderAuth();toast("Admin session authenticated.","success");addAudit("LOGIN")}else document.getElementById("loginError").classList.remove("hidden")}
function selectFile(file){if(!file)return;const ext=file.name.split(".").pop().toLowerCase();if(!ALLOWED.includes(ext)){toast(`File type .${ext} is not supported.`,"error");return}if(file.size>MAX_FILE_SIZE){toast("File exceeds the 500 MB application limit.","error");return}selectedFile=file;document.getElementById("fileName").textContent=`${file.name} (${formatBytes(file.size)})`;document.getElementById("uploadStatus").textContent="File ready for upload."}
async function upload(e){e.preventDefault();if(!selectedFile){toast("Please select a file first.","error");return}const model=document.getElementById("uploadModel").value,key=document.getElementById("uploadRecord").value,note=document.getElementById("uploadNote").value.trim(),item=data[model].items[key],btn=document.getElementById("saveUploadBtn"),progressWrap=document.getElementById("uploadProgressWrap"),progress=document.getElementById("uploadProgress");btn.disabled=true;progressWrap.classList.remove("hidden");progress.style.width="20%";try{await saveFile(`${model}_${key}`,selectedFile);progress.style.width="70%";item.filename=selectedFile.name;item.size=formatBytes(selectedFile.size);if(note)item.tags=[note];saveData();await addAudit("UPLOAD",{model,key,filename:selectedFile.name,size:selectedFile.size});progress.style.width="100%";renderAll();closeModal("uploadModal");toast(`${selectedFile.name} saved successfully.`,`success`);selectedFile=null;document.getElementById("uploadForm").reset();document.getElementById("uploadModel").value=currentModel;document.getElementById("fileName").textContent="Drop file here or click to browse"}catch{toast("Could not save the file to IndexedDB.","error")}finally{btn.disabled=false;setTimeout(()=>progressWrap.classList.add("hidden"),300)}}
async function downloadRecord(key,filename){try{const record=await getFile(key);if(record?.blob){downloadBlob(record.blob,record.filename||filename);await addAudit("DOWNLOAD",{key,filename});return}}catch{}downloadText(`Mobile R&D Engineering Portal\nModel: ${currentModel}\nRecord: ${key}\nFile: ${filename}\nGenerated: ${new Date().toISOString()}`,filename||`${key}.txt`,"text/plain");toast("No local binary was found; generated a reference file instead.","info")}
function recordData(key){return currentItems()[key]}
function copyRecord(key){const i=recordData(key);const text=`Record ${key}\nTitle: ${i.title}\nCategory: ${i.category}\nTags: ${(i.tags||[]).join(", ")}\nFile: ${i.filename||"—"}\nSize: ${i.size||"—"}`;navigator.clipboard.writeText(text);toast(`Record ${key} copied.`,`success`)}
function copyLink(key){const url=`${location.href.split("#")[0]}#record/${currentModel}/${key}`;navigator.clipboard.writeText(url);toast("Record link copied.","success")}
function copySpecs(){const m=data[currentModel].meta;navigator.clipboard.writeText(`Model: ${currentModel} (${m.name})\nProcessor: ${m.ap}\nModem/RF: ${m.modem}\nSW Build: ${m.swVersion}\nHQ Lead: ${m.leadKorea}\nStatus: ${m.status}`);toast("Model specification copied.","success")}
function exportModel(){downloadText(JSON.stringify(data[currentModel],null,2),`${currentModel}_Engineering_Master.json`);toast("Model JSON exported.","success")}
function exportReport(){const m=data[currentModel].meta,rows=filteredEntries().map(([k,i])=>`${k} | ${i.title} | ${i.category} | ${i.filename||`${i.subItems?.length||0} linked files`}`).join("\n");downloadText(`MOBILE R&D ENGINEERING REPORT\n================================\nModel: ${currentModel} - ${m.name}\nStatus: ${m.status}\nProcessor: ${m.ap}\nModem/RF: ${m.modem}\nSW Build: ${m.swVersion}\nHQ Lead: ${m.leadKorea}\n\nRECORDS\n-------\n${rows}\n\nGenerated: ${new Date().toISOString()}`,`${currentModel}_Engineering_Report.txt`,"text/plain");toast("Engineering report exported.","success")}
function exportSelected(){const rows=[...selectedRecords].map(k=>({key:k,...recordData(k)}));if(!rows.length)return;downloadText(JSON.stringify({model:currentModel,records:rows},null,2),`${currentModel}_Selected_Records.json`);toast(`${rows.length} records exported.`,`success`)}
function printSelected(){const keys=selectedRecords.size?[...selectedRecords]:filteredEntries().map(x=>x[0]);if(!keys.length)return;const m=data[currentModel].meta;const html=`<html><head><title>${currentModel} Engineering Records</title><style>body{font-family:Arial;padding:30px;color:#111}h1{font-size:20px}h2{font-size:15px;margin-top:24px}p,li{font-size:12px}section{border:1px solid #ddd;padding:14px;margin:10px 0;border-radius:8px}</style></head><body><h1>Mobile R&D Engineering Portal — ${currentModel}</h1><p>${m.name} · ${m.status} · ${m.ap} · ${m.modem} · ${m.swVersion}</p>${keys.map(k=>{const i=recordData(k);return `<section><h2>${k} — ${escapeHtml(i.title)}</h2><p>Category: ${escapeHtml(i.category)}</p><p>Tags: ${escapeHtml((i.tags||[]).join(", "))}</p><p>File: ${escapeHtml(i.filename||"—")}</p></section>`}).join("")}</body></html>`;const w=window.open("","_blank");w.document.write(html);w.document.close();w.focus();setTimeout(()=>w.print(),250)}
function openCompare(){const modelA=document.getElementById("compareModelA"),modelB=document.getElementById("compareModelB");modelA.innerHTML=MODEL_ORDER.map(m=>`<option>${m}</option>`).join("");modelB.innerHTML=MODEL_ORDER.map(m=>`<option>${m}</option>`).join("");modelA.value=currentModel;modelB.value=MODEL_ORDER.find(m=>m!==currentModel)||MODEL_ORDER[0];renderComparison();openModal("compareModal")}
function renderComparison(){const a=document.getElementById("compareModelA").value,b=document.getElementById("compareModelB").value,body=document.getElementById("compareBody");const rows=RECORD_ORDER.map(k=>{const x=currentItemsFor(a)[k],y=currentItemsFor(b)[k];if(!x&&!y)return "";const same=JSON.stringify(x)===JSON.stringify(y);return `<tr class="${same?"same":"different"}"><th>${k}</th><td><strong>${escapeHtml(x?.title||"—")}</strong><br><small>${escapeHtml(x?.category||"")} · ${escapeHtml(x?.filename||"")}</small></td><td><strong>${escapeHtml(y?.title||"—")}</strong><br><small>${escapeHtml(y?.category||"")} · ${escapeHtml(y?.filename||"")}</small></td></tr>`}).join("");body.innerHTML=`<table class="compare-table"><thead><tr><th>Record</th><th>${a}</th><th>${b}</th></tr></thead><tbody>${rows}</tbody></table>`}
function openPresentation(key){const i=recordData(key);if(!i)return;document.getElementById("presentationContent").innerHTML=`<div class="presentation-code">${currentModel} · RECORD ${key}</div><h2>${escapeHtml(i.title)}</h2><div class="presentation-category">${escapeHtml(i.category)}</div><div class="presentation-tags">${(i.tags||[]).map(t=>`<span class="tag">${escapeHtml(t)}</span>`).join("")}</div><div class="presentation-file"><strong>File</strong><span>${escapeHtml(i.filename||"Linked record")}</span></div>`;openModal("presentationModal")}
function navigateRecord(delta){const arr=RECORD_ORDER.filter(k=>currentItems()[k]);const idx=arr.indexOf(location.hash.split("/").pop());const next=arr[Math.max(0,Math.min(arr.length-1,(idx<0?0:idx)+delta))];if(next)openRecord(next)}
async function resetData(){if(!confirm("Reset all local dashboard data and stored files? This cannot be undone."))return;data=createDefaultData();saveData();await deleteAllFiles();await addAudit("RESET");currentModel=MODEL_ORDER[0];activeCategory="all";query="";selectedRecords.clear();renderCategories();renderAll();closeModal("settingsModal");toast("Local data reset to default dataset.","success")}
function dateStamp(){return new Date().toISOString().slice(0,10).replaceAll("-","")}
init();
